<?php

/*
|--------------------------------------------------------------------------
| Universal PDF Template
|--------------------------------------------------------------------------
|
| Variables available:
|
| $title
| $data
|
*/

?>
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<style>

*{

    box-sizing:border-box;
    font-family:DejaVu Sans,sans-serif;

}

body{

    font-size:12px;
    color:#222;

}

.header{

    text-align:center;
    border-bottom:2px solid #333;
    padding-bottom:12px;
    margin-bottom:20px;

}

.header h1{

    margin:0;
    font-size:24px;

}

.header h2{

    margin:6px 0;
    font-size:18px;

}

.header p{

    margin:2px;

}

.info{

    margin-bottom:15px;
    font-size:11px;

}

table{

    width:100%;
    border-collapse:collapse;

}

th{

    background:#2c3e50;
    color:#fff;
    border:1px solid #666;
    padding:8px;
    text-align:left;

}

td{

    border:1px solid #bbb;
    padding:7px;

}

tr:nth-child(even){

    background:#f4f4f4;

}

.footer{

    margin-top:25px;
    border-top:1px solid #999;
    text-align:center;
    font-size:10px;
    color:#666;
    padding-top:8px;

}

</style>

</head>

<body>

<div class="header">

    <h1>MR Tailor</h1>

    <h2><?= htmlspecialchars(ucwords($title)) ?></h2>

    <p>
        Generated:
        <?= date('d M Y h:i A') ?>
    </p>

</div>

<div class="info">

<strong>Total Records :</strong>

<?= count($data) ?>

</div>

<?php if(empty($data)): ?>

<p>No records found.</p>

<?php else: ?>

<table>

<thead>

<tr>

<?php foreach(array_keys($data[0]) as $column): ?>

<th>

<?= htmlspecialchars(ucwords(str_replace('_',' ',$column))) ?>

</th>

<?php endforeach; ?>

</tr>

</thead>

<tbody>

<?php foreach($data as $row): ?>

<tr>

<?php foreach($row as $value): ?>

<td>

<?= htmlspecialchars((string)$value) ?>

</td>

<?php endforeach; ?>

</tr>

<?php endforeach; ?>

</tbody>

</table>

<?php endif; ?>

<div class="footer">

Generated by MR Tailor Management System

</div>

</body>

</html>